src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/dpr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import polls.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include(polls.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/templates/_brandname.html
Dpr

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Reports & Ratings </a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Knowledge & Education</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Other Services </a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Terms & Conditions</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Customer Support</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">Digital profile reporting (Dpr) has arrived and is here to stay!</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://i.imgur.com/IsCBcuo.png" alt="profile pic"></div>
        <p class="heavy text-center">Arshpreet Singh</p>
        <h2>Data-Scientist</h2>
        <p>Arshpreet provides automated solutions through research and development. He works in the Research
Management office where he performs in multiple fields which include data science, machine learning,
parallel computing, and computer algebraic systems. Arshpreet has previously worked in the field of
quantitative finance using machine learning and applied mathematics to generate trading strategies. He
is also responsible for managing the algorithm for Dpr.</p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://i.imgur.com/XELBhPr.png" alt="profile pic"></div>
        <p class="heavy text-center">Nina Kojevnikov</p>
        <h2>Writer & Editor</h2>
        <p>Nina has taught language and writing skills worldwide. She has edited and co-authored publications and
training materials in a wide spectrum of fields, including management and leadership, women’s issues,
humanitarian, corporate, education, legal, chemical weapons’ disarmament and content writing for public
websites. Nina is a former Professor of Writing, English, and Literature at Webster University in Leiden,
the Netherlands. She is also a member of the Graduate Associate Faculty of Lesley University in
Cambridge, Massachusetts.</p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://i.imgur.com/Uo3kPlz.png" alt="profile pic"></div>
        <p class="heavy text-center">Marsha Jones</p>
        <h2>CEO</h2>
        <p>Marsha is the digital business management guru. Her background includes multitasking in administration,
business strategy, and technology management. The latter combination lead Marsha to specializing in
data analysis, business modeling, business processes, and application development via project
management. She was also recognized by an organization when it received the Nobel Peace prize.
Marsha can work and operate across cultures and geographical locations. She has lived and worked in
North America, Europe, and Africa.</p>


      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Emporia Consultancy</strong><br>
            Delaware<br>
            <abbr>Email:</abbr>ec@emporiaconsultancy.com
            <abbr>Tel</abbr> +1 302-613-1222
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% comment %}
Google map for later use
{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}
{% endcomment %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}
    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>

        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>

                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}
{% block navbar-left %}

  {% include "_navbar.html" with active_link="home" %}

{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  
{% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>

          <p>A reporting and rating service to assist HR departments,
 Organizations, businesses, and individuals with obtaining, understanding, and managing
digital profiles on the Internet.</p>
	

  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>What is a digital profile?</h2>

      <p>Profiling is the process of building a profile using information collected from available data. In general terms, a profile is a description of characteristics of a
person or entity. A digital profile extends the latter term to include a digital representation, of a person or entity, which considers the characteristics and
preferences of their online activity.
<br>
Digital footprints are a unique set of online activities, actions, and communications that leave a data trace on the Internet, computers, and other devices. It
includes activities such as websites you visit, emails you send, and information you submit to online services.
</p>
      
<p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Managing your reputation</h2>
      <p>
Create a positive digital footprint. The data you create online tells others such as Employers, Universities, Law Enforcement, Teachers, and Parents
what you have said, what others have said about you, images of you tagged online, browsing habits, personal information, and the most important, social media
profiles. What does your digital footprint reveal?

</p>
      

<p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Dpr Reporting and Rating</h2>
      <p>

Just as a person or entity manages their credit reports and scores via Experian or Moody’s for example, it is now necessary in the world we live in today to know
if our digital profiles are positive, average, or negative.
<br>
Why? Because our reports and ratings help entities and individuals to understand the consequences of desired or undesired behavior that may be revealed. For
example, our reports and ratings can help HR or Talent Management select the appropriate candidate for a job (keep in mind that some entities are looking for
candidates with undesirable behavior because that is their brand). Or they can inform job applicants what potential employers may learn about their online
activities and provide them the opportunity to clean up their digital if applicable. Further, this service will help entities maintain sustainable reputations and
guard against negative impressions.
</p>
      

<p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}